services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bdfolhetodigital
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/sql:/docker-entrypoint-initdb.d
    command: >
      --authentication-policy=mysql_native_password
      --host-cache-size=0
      --skip-name-resolve
    networks:
      - app-network
volumes:
  db_data:
  
networks:
  app-network:
    driver: bridge
